const ALLOWED_IMAGE_MIME_TYPES = Object.freeze(["image/jpeg", "image/png", "image/webp"]);
const ALLOWED_IMAGE_EXTENSIONS = Object.freeze([".jpg", ".jpeg", ".png", ".webp"]);
const MAX_IMAGE_SIZE_BYTES = 8 * 1024 * 1024;
const MAX_IMAGE_DIMENSION = 8000;
const MIN_IMAGE_DIMENSION = 120;
const STANDARD_IMAGE_MAX_DIMENSION = 1600;
const THUMBNAIL_IMAGE_MAX_DIMENSION = 360;

module.exports = {
  ALLOWED_IMAGE_EXTENSIONS,
  ALLOWED_IMAGE_MIME_TYPES,
  MAX_IMAGE_DIMENSION,
  MAX_IMAGE_SIZE_BYTES,
  MIN_IMAGE_DIMENSION,
  STANDARD_IMAGE_MAX_DIMENSION,
  THUMBNAIL_IMAGE_MAX_DIMENSION,
};
