const REPORT_CATEGORIES = Object.freeze({
  ROADS: "ROADS",
  WASTE_MANAGEMENT: "WASTE_MANAGEMENT",
  WATER: "WATER",
  ELECTRICITY: "ELECTRICITY",
  TRAFFIC: "TRAFFIC",
  PUBLIC_WORKS: "PUBLIC_WORKS",
  OTHER: "OTHER",
});

module.exports = {
  REPORT_CATEGORIES,
};
