const REPORT_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  AI_ANALYZED: "AI_ANALYZED",
  VERIFICATION_PENDING: "VERIFICATION_PENDING",
  VERIFIED: "VERIFIED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CITIZEN_CONFIRMATION: "CITIZEN_CONFIRMATION",
  CLOSED: "CLOSED",
  REJECTED: "REJECTED",
  DUPLICATE: "DUPLICATE",
  NEEDS_MORE_INFORMATION: "NEEDS_MORE_INFORMATION",
  DISPUTED: "DISPUTED",
  REOPENED: "REOPENED",
});

module.exports = {
  REPORT_STATUSES,
};
